In [1]:

data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv'

!wget $data -O data-week-3.csv

--2026-09-21 22:32:50--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 278746 (272K) [text/plain]
Saving to: ‘data-week-3.csv’

data-week-3.csv     100%[===================>] 272.21K  --.-KB/s    in 0.05s

2026-09-21 22:32:52 (5.10 MB/s) - ‘data-week-3.csv’ saved [278746/278746]

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("data-week-3.csv")

In [4]:
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [5]:
df.head().T

,0,1,2,3,4
lead_source,organic_search,social_media,referral,paid_ads,referral
industry,technology,technology,retail,manufacturing,manufacturing
employment_status,employed,employed,employed,student,student
location,europe,south_america,europe,NaN,north_america
annual_income,88160.0,72688.0,44697.0,NaN,24062.0
number_of_courses_viewed,3,3,3,3,4
interaction_count,4,7,4,6,5
lead_score,0.64,0.72,0.58,0.57,0.62
converted,1,1,1,0,1

In [6]:
categorical_features=list(df.dtypes[df.dtypes=="string"].index)

In [7]:
df[categorical_features]=df[categorical_features].fillna('NA')

In [8]:
df[categorical_features].isnull().sum()

lead_source          0
industry             0
employment_status    0
location             0
dtype: int64

In [9]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [10]:
numerical_features=["annual_income","number_of_courses_viewed","interaction_count","lead_score","converted"]

In [11]:
numerical_features

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score',
 'converted']

In [12]:
df[numerical_features].isnull().sum()

annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [13]:
df[numerical_features]=df[numerical_features].fillna(0)

In [14]:
df[numerical_features].isnull().sum()

annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [15]:
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [16]:
numerical_features=["annual_income","number_of_courses_viewed","interaction_count","lead_score"]

In [17]:
df["industry"].mode()

0    technology
Name: industry, dtype: str

In [18]:
from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [19]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [20]:
len(df_train),len(df_val),len(df_test)

(3000, 1000, 1000)

In [21]:
df_train=df_train.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)

In [22]:
y_train=df_train.converted.values
y_val=df_val.converted.values
y_test=df_test.converted.values

In [23]:
del df_train["converted"]
del df_val["converted"]
del df_test["converted"]

In [24]:
df_full_train = df_full_train.reset_index(drop=True)

In [25]:
df_full_train.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [26]:
df_full_train[numerical_features].corrwith(df_full_train.converted).abs()

annual_income               0.189723
number_of_courses_viewed    0.391005
interaction_count           0.451268
lead_score                  0.482188
dtype: float64

In [27]:
from sklearn.metrics import mutual_info_score

In [28]:
def mutual_info_converted_score(series):
    return round(mutual_info_score(series, df_full_train.converted),2)

In [29]:
mi = df_full_train[categorical_features].apply(mutual_info_converted_score)
mi.sort_values(ascending=False)

lead_source          0.03
employment_status    0.02
industry             0.00
location             0.00
dtype: float64

In [30]:
dicts=df[categorical_features+numerical_features].to_dict(orient="records")

In [31]:
dicts

[{'lead_source': 'organic_search',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 88160.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 4,
  'lead_score': 0.64},
 {'lead_source': 'social_media',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 72688.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.72},
 {'lead_source': 'referral',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 44697.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 4,
  'lead_score': 0.58},
 {'lead_source': 'paid_ads',
  'industry': 'manufacturing',
  'employment_status': 'student',
  'location': 'NA',
  'annual_income': 0.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 6,
  'lead_score': 0.57},
 {'lead_source': 'referral',
  'industry': 'manufacturing',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 24062.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 5,
  'lead_score': 0.62},
 {'lead_source': 'referral',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 43841.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.77},
 {'lead_source': 'NA',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 58738.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 9,
  'lead_score': 0.78},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 95059.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.41},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 62565.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 6,
  'lead_score': 0.52},
 {'lead_source': 'referral',
  'industry': 'retail',
  'employment_status': 'student',
  'location': 'asia',
  'annual_income': 12000.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 2,
  'lead_score': 0.35},
 {'lead_source': 'referral',
  'industry': 'retail',
  'employment_status': 'NA',
  'location': 'europe',
  'annual_income': 43935.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 9,
  'lead_score': 0.78},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 80773.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.72},
 {'lead_source': 'social_media',
  'industry': 'NA',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 47115.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 0,
  'lead_score': 0.11},
 {'lead_source': 'paid_ads',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 62439.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.33},
 {'lead_source': 'paid_ads',
  'industry': 'retail',
  'employment_status': 'student',
  'location': 'asia',
  'annual_income': 12000.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 1,
  'lead_score': 0.13},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 59239.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 9,
  'lead_score': 0.85},
 {'lead_source': 'organic_search',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 37431.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.55},
 {'lead_source': 'organic_search',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 83331.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.56},
 {'lead_source': 'referral',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 49038.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.5},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'unemployed',
  'location': 'asia',
  'annual_income': 50544.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 2,
  'lead_score': 0.4},
 {'lead_source': 'social_media',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 31638.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.47},
 {'lead_source': 'social_media',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 65430.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.73},
 {'lead_source': 'social_media',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 57952.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 5,
  'lead_score': 0.56},
 {'lead_source': 'referral',
  'industry': 'healthcare',
  'employment_status': 'student',
  'location': 'europe',
  'annual_income': 0.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 10,
  'lead_score': 0.76},
 {'lead_source': 'organic_search',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 65713.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 7,
  'lead_score': 0.74},
 {'lead_source': 'referral',
  'industry': 'retail',
  'employment_status': 'student',
  'location': 'asia',
  'annual_income': 0.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 5,
  'lead_score': 0.53},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 42510.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 5,
  'lead_score': 0.6},
 {'lead_source': 'paid_ads',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 45257.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.32},
 {'lead_source': 'paid_ads',
  'industry': 'NA',
  'employment_status': 'self_employed',
  'location': 'europe',
  'annual_income': 82749.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 1,
  'lead_score': 0.34},
 {'lead_source': 'referral',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 45317.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 8,
  'lead_score': 0.83},
 {'lead_source': 'social_media',
  'industry': 'NA',
  'employment_status': 'student',
  'location': 'south_america',
  'annual_income': 51061.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.37},
 {'lead_source': 'events',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 13171.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.5},
 {'lead_source': 'social_media',
  'industry': 'retail',
  'employment_status': 'self_employed',
  'location': 'africa',
  'annual_income': 33862.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.5},
 {'lead_source': 'paid_ads',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 68156.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 5,
  'lead_score': 0.48},
 {'lead_source': 'paid_ads',
  'industry': 'retail',
  'employment_status': 'unemployed',
  'location': 'asia',
  'annual_income': 26032.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.4},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 65643.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 6,
  'lead_score': 0.62},
 {'lead_source': 'social_media',
  'industry': 'education',
  'employment_status': 'self_employed',
  'location': 'south_america',
  'annual_income': 39539.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 4,
  'lead_score': 0.37},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 47583.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 5,
  'lead_score': 0.6},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 92267.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 3,
  'lead_score': 0.42},
 {'lead_source': 'referral',
  'industry': 'education',
  'employment_status': 'self_employed',
  'location': 'north_america',
  'annual_income': 61949.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.38},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'unemployed',
  'location': 'north_america',
  'annual_income': 39207.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.3},
 {'lead_source': 'paid_ads',
  'industry': 'education',
  'employment_status': 'student',
  'location': 'europe',
  'annual_income': 12000.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 0,
  'lead_score': 0.11},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 73254.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.48},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'self_employed',
  'location': 'south_america',
  'annual_income': 56082.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.49},
 {'lead_source': 'social_media',
  'industry': 'manufacturing',
  'employment_status': 'student',
  'location': 'asia',
  'annual_income': 14763.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 5,
  'lead_score': 0.42},
 {'lead_source': 'social_media',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 53769.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 6,
  'lead_score': 0.55},
 {'lead_source': 'events',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 40215.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 6,
  'lead_score': 0.54},
 {'lead_source': 'organic_search',
  'industry': 'finance',
  'employment_status': 'self_employed',
  'location': 'north_america',
  'annual_income': 67761.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 8,
  'lead_score': 0.83},
 {'lead_source': 'social_media',
  'industry': 'education',
  'employment_status': 'student',
  'location': 'south_america',
  'annual_income': 12000.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 0,
  'lead_score': 0.16},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 69440.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 6,
  'lead_score': 0.55},
 {'lead_source': 'organic_search',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 35181.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 8,
  'lead_score': 0.76},
 {'lead_source': 'social_media',
  'industry': 'retail',
  'employment_status': 'unemployed',
  'location': 'asia',
  'annual_income': 24782.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.42},
 {'lead_source': 'events',
  'industry': 'finance',
  'employment_status': 'self_employed',
  'location': 'europe',
  'annual_income': 75980.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 10,
  'lead_score': 0.84},
 {'lead_source': 'social_media',
  'industry': 'technology',
  'employment_status': 'unemployed',
  'location': 'north_america',
  'annual_income': 59104.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 3,
  'lead_score': 0.34},
 {'lead_source': 'organic_search',
  'industry': 'technology',
  'employment_status': 'student',
  'location': 'south_america',
  'annual_income': 36980.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 7,
  'lead_score': 0.72},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 67391.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 4,
  'lead_score': 0.63},
 {'lead_source': 'paid_ads',
  'industry': 'healthcare',
  'employment_status': 'unemployed',
  'location': 'north_america',
  'annual_income': 30925.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.28},
 {'lead_source': 'social_media',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 69200.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.46},
 {'lead_source': 'social_media',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 50582.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.41},
 {'lead_source': 'events',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 57378.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 2,
  'lead_score': 0.3},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'self_employed',
  'location': 'south_america',
  'annual_income': 52321.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.67},
 {'lead_source': 'referral',
  'industry': 'healthcare',
  'employment_status': 'unemployed',
  'location': 'asia',
  'annual_income': 32909.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.44},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 48800.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 5,
  'lead_score': 0.51},
 {'lead_source': 'referral',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 61508.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 6,
  'lead_score': 0.71},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 78409.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 3,
  'lead_score': 0.4},
 {'lead_source': 'social_media',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 59455.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 1,
  'lead_score': 0.34},
 {'lead_source': 'referral',
  'industry': 'healthcare',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 40555.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.47},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 60187.0,
  'number_of_courses_viewed': 5,
  'interaction_count': 8,
  'lead_score': 0.81},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 45260.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 4,
  'lead_score': 0.56},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 62838.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.53},
 {'lead_source': 'paid_ads',
  'industry': 'retail',
  'employment_status': 'self_employed',
  'location': 'north_america',
  'annual_income': 52734.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.66},
 {'lead_source': 'paid_ads',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 49431.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.41},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'NA',
  'annual_income': 85628.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 4,
  'lead_score': 0.55},
 {'lead_source': 'social_media',
  'industry': 'NA',
  'employment_status': 'unemployed',
  'location': 'europe',
  'annual_income': 18517.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 3,
  'lead_score': 0.39},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 56281.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 6,
  'lead_score': 0.63},
 {'lead_source': 'social_media',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 42788.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 7,
  'lead_score': 0.75},
 {'lead_source': 'events',
  'industry': 'manufacturing',
  'employment_status': 'self_employed',
  'location': 'north_america',
  'annual_income': 48635.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 5,
  'lead_score': 0.44},
 {'lead_source': 'NA',
  'industry': 'education',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 0.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 2,
  'lead_score': 0.22},
 {'lead_source': 'social_media',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 27411.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 0,
  'lead_score': 0.01},
 {'lead_source': 'events',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 71331.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.39},
 {'lead_source': 'organic_search',
  'industry': 'technology',
  'employment_status': 'self_employed',
  'location': 'europe',
  'annual_income': 82020.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.51},
 {'lead_source': 'paid_ads',
  'industry': 'finance',
  'employment_status': 'student',
  'location': 'europe',
  'annual_income': 47798.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.21},
 {'lead_source': 'referral',
  'industry': 'education',
  'employment_status': 'student',
  'location': 'europe',
  'annual_income': 25275.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 3,
  'lead_score': 0.31},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 56758.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 5,
  'lead_score': 0.53},
 {'lead_source': 'paid_ads',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 33395.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.3},
 {'lead_source': 'organic_search',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 59268.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.44},
 {'lead_source': 'paid_ads',
  'industry': 'finance',
  'employment_status': 'self_employed',
  'location': 'asia',
  'annual_income': 82824.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 3,
  'lead_score': 0.42},
 {'lead_source': 'NA',

In [32]:
from sklearn.feature_extraction import DictVectorizer

In [33]:
dv = DictVectorizer(sparse=False)

In [34]:
train_dict = df_train[categorical_features+numerical_features].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [35]:
X_train.shape

(3000, 28)

In [36]:
val_dict = df_val[categorical_features+numerical_features].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [37]:
X_val.shape

(1000, 28)

In [38]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
# solver='lbfgs' is the default solver in newer version of sklearn
# for older versions, you need to specify it explicitly
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [39]:
y_pred = model.predict_proba(X_val)[:, 1]

In [40]:
coverted_decision = (y_pred >= 0.5)

In [41]:
round((y_val == coverted_decision).mean(),2)

np.float64(0.65)

In [42]:
from copy import copy

In [43]:
# test_numerical_features=copy(numerical_features)
# test_numerical_features.remove("interaction_count")

In [44]:
# test_numerical_features

In [45]:
def make_model(features):
        dv = DictVectorizer(sparse=False)
        
        train_dict = df_train[features].to_dict(orient='records')
        val_dict = df_val[features].to_dict(orient='records')
        
    
        X_train = dv.fit_transform(train_dict)
    
        X_val = dv.transform(val_dict)
    
        model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
        # solver='lbfgs' is the default solver in newer version of sklearn
        # for older versions, you need to specify it explicitly
        model.fit(X_train, y_train)

        return model,X_val


def diff_og_without_feature(features):

    model,X_val=make_model(features)

    y_pred = model.predict_proba(X_val)[:, 1]

    coverted_decision = (y_pred >= 0.5)
    og= (y_val == coverted_decision).mean()

    for f_remove in features:
        r = calulate_without_features(f_remove,features)
        print(f" difference between og_score {og} and without_feature_{f_remove} is {og-r}") 

def calulate_without_features(f_remove,features):
   
    test_features=copy(features)
    test_features.remove(f_remove)
    model, X_val = make_model(test_features)

    y_pred = model.predict_proba(X_val)[:, 1]

    coverted_decision = (y_pred >= 0.5)
    r= (y_val == coverted_decision).mean()

    return r

In [46]:
diff_og_without_feature(categorical_features+numerical_features)

 difference between og_score 0.651 and without_feature_lead_source is 0.0030000000000000027
 difference between og_score 0.651 and without_feature_industry is 0.0
 difference between og_score 0.651 and without_feature_employment_status is 0.0030000000000000027
 difference between og_score 0.651 and without_feature_location is 0.0010000000000000009
 difference between og_score 0.651 and without_feature_annual_income is -0.06499999999999995
 difference between og_score 0.651 and without_feature_number_of_courses_viewed is 0.006000000000000005
 difference between og_score 0.651 and without_feature_interaction_count is 0.05800000000000005
 difference between og_score 0.651 and without_feature_lead_score is 0.0

In [47]:
categorical_features+numerical_features

['lead_source',
 'industry',
 'employment_status',
 'location',
 'annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [48]:
for C in [0.000001, 0.00001, 0.0001, 0.001]:
    dv = DictVectorizer(sparse=False)

    train_dict = df_train[categorical_features + numerical_features].to_dict(orient='records')
    val_dict = df_val[categorical_features + numerical_features].to_dict(orient='records')

    X_train = dv.fit_transform(train_dict)
    X_val = dv.transform(val_dict)

    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict_proba(X_val)[:, 1]
    converted_decision = (y_pred >= 0.5)

    print(C, round((y_val == converted_decision).mean(), 3))

1e-06 0.59
1e-05 0.59
0.0001 0.59
0.001 0.648